[package]
name = "pam-gxfp51b7"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "pam_gxfp51b7"
crate-type = ["cdylib"]

[dependencies]
pam.workspace = true
nix.workspace = true
rustix.workspace = true
libc.workspace = true
