[package]
name = "gxfp51b7"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gxfp-backends = { path = "../backends" }
gxfp-core = { path = "../core" }
anyhow.workspace = true
clap.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
wait-timeout.workspace = true
memmap2 = "0.9"

[lints]
workspace = true
