# SPDX-License-Identifier: GPL-2.0-only OR LGPL-3.0-or-later
PACKAGE_NAME="gxfp51b7-bios"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="goodix_bios_read"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
