[package]
name = "gxfp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ndarray.workspace = true
ndarray-conv.workspace = true
ndarray-ndimage.workspace = true
ndarray-npy.workspace = true
serde.workspace = true
interpn = "0.11"
rustfft = "6"
